# -*- coding: utf-8 -*-
"""Призывники

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pKz5wcBVH1wgYtQk0V46WeyXgvnqDFVY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('Priziv1volna.txt', sep='\t')

"""Mobilization data consists of 306 thousand people"""

df.shape

"""Filtering out birth year"""

df['YEAR'] = df['ДАТА_РОЖДЕНИЯ'].apply(lambda x: int(x[-4:]))

df.head()

year_counts = df['YEAR'].value_counts()

"""Scatter plot shows the amount of people mobilized per every birth year"""

plt.scatter(year_counts.index, year_counts.values)
plt.xlabel('Birth year')
plt.ylabel('Total people')

"""Filtering out cities out of address"""

df['city'] = df['АДРЕС'].apply(lambda x: x.split(', ')[0])

city_counts = df['city'].value_counts()

"""Amount of mobilized people from Saint-Petersburg (2nd lardest city)"""

df['city'].str.contains('САНКТ-ПЕТЕРБУРГ').sum()

"""Amount of mobilized people from Moscow"""

df['city'].str.contains('МОСКВА').sum()

"""Oveall per-region non-filtered stats"""

city_counts.head(30)